/**
 * IPA — Indexed Packet Asset (deal data resolution layer.
 *
 * DealRoom citations are backed by the seed corpus index (`deal-index.json`,
 * generated by `npm run seed`). This module is the read-side query surface
 * the UI uses: page lookup, section resolution, and anchor text.
 */

import dealIndex from '../data/deal-index.json'

export interface IpBlock {
  role: 'title' | 'section' | 'statement' | 'body'
  text: string
}

export interface IpPage {
  documentId: string
  page: number
  section?: string
  blocks: IpBlock[]
}

export interface IpSection {
  documentId: string
  name: string
  start: number
  end: number
}

export interface IpIndex {
  format: 'dealroom/ipa-index/v1'
  generatedAt: string
  documents: { id: string; filename: string; type: string; pagesTotal: number }[]
  sections: IpSection[]
  pages: IpPage[]
}

export const ipIndex = dealIndex as unknown as IpIndex

/** All blocks on a document page, in layout order. */
export function pageBlocks(documentId: string, page: number): IpBlock[] {
  const p = ipIndex.pages.find((x) => x.documentId === documentId && x.page === page)
  return p?.blocks ?? []
}

/** Section names covering the page, or null when the page is indexed. */
export function pageSectionLabel(documentId: string, page: number): string | null {
  const p = ipIndex.pages.find((x) => x.documentId === documentId && x.page === page)
  return p?.section ?? null
}

/** Whether a citation anchor resolves to an indexed page. */
export function isIndexed(documentId: string, page: number): boolean {
  return ipIndex.pages.some((x) => x.documentId === documentId && x.page === page)
}